# Generated by Django 2.2.6 on 2019-10-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
                ('company_add', models.CharField(max_length=128)),
                ('company_phone_nub', models.CharField(max_length=16)),
            ],
        ),
    ]
