# Generated by Django 2.2.6 on 2019-10-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='company_email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='company_key_word',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_add',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_phone_nub',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
