# Generated by Django 2.2.6 on 2019-10-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four', '0002_auto_20191016_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('four_title', models.CharField(max_length=5)),
                ('four_one_words', models.CharField(max_length=10)),
                ('four_detail_words', models.CharField(max_length=140)),
            ],
        ),
    ]
