# Generated by Django 2.2.6 on 2019-10-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four', '0003_fourinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourinfo',
            name='four_detail_words',
            field=models.TextField(max_length=200),
        ),
    ]
