# Generated by Django 2.2.6 on 2019-10-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four', '0005_auto_20191016_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydata',
            options={'verbose_name': '首页：公司信息', 'verbose_name_plural': '首页：公司信息'},
        ),
        migrations.AlterModelOptions(
            name='fourinfo',
            options={'verbose_name': '首页：四个案例信息', 'verbose_name_plural': '首页：四个案例信息'},
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_add',
            field=models.CharField(max_length=128, null=True, verbose_name='首页：公司地址'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_email',
            field=models.CharField(max_length=20, null=True, verbose_name='首页：公司邮件'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_key_word',
            field=models.CharField(max_length=60, null=True, verbose_name='首页：公司属性（SEO）'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_name',
            field=models.CharField(max_length=128, null=True, verbose_name='首页：公司名字'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_phone_nub',
            field=models.CharField(max_length=16, null=True, verbose_name='首页：公司电话'),
        ),
        migrations.AlterField(
            model_name='fourinfo',
            name='four_detail_words',
            field=models.TextField(max_length=500, verbose_name='详细介绍'),
        ),
        migrations.AlterField(
            model_name='fourinfo',
            name='four_one_words',
            field=models.CharField(max_length=10, verbose_name='四个标题中的一个'),
        ),
        migrations.AlterField(
            model_name='fourinfo',
            name='four_title',
            field=models.CharField(max_length=5, verbose_name='四个字中的一个'),
        ),
    ]
