# Generated by Django 2.2.6 on 2019-10-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=30)),
                ('pro_introduction', models.CharField(max_length=140)),
                ('pro_img_face', models.ImageField(upload_to='products_images/')),
                ('pro_information', models.TextField(max_length=1000)),
            ],
        ),
    ]
