# Generated by Django 2.2.6 on 2019-10-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191017_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='pro_img_face',
            field=models.ImageField(upload_to='home/products_upload_images/'),
        ),
    ]
