# Generated by Django 2.2.6 on 2019-10-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_productslist_pro_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='pro_img_face',
            field=models.ImageField(upload_to='products_upload_images/', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='pro_information',
            field=models.TextField(max_length=1000, verbose_name='详细介绍'),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='pro_introduction',
            field=models.CharField(max_length=140, verbose_name='简单介绍'),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='pro_time',
            field=models.TimeField(null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='pro_title',
            field=models.CharField(max_length=30, verbose_name='标题'),
        ),
    ]
