# Generated by Django 2.2.6 on 2019-10-18 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191018_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productslist',
            options={'verbose_name': '案例列表', 'verbose_name_plural': '案例列表'},
        ),
    ]
