# Generated by Django 2.2.6 on 2019-10-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191018_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='pro_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
    ]
