# Generated by Django 2.2.6 on 2019-10-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191018_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=10, verbose_name='客户名')),
                ('client_email', models.EmailField(max_length=254, null=True, verbose_name='客户邮箱')),
                ('client_phone', models.CharField(max_length=20, verbose_name='客户电话')),
                ('client_message', models.CharField(max_length=200, null=True, verbose_name='客户留言')),
            ],
            options={
                'verbose_name': '客户留言',
                'verbose_name_plural': '客户留言',
            },
        ),
    ]
