# Generated by Django 2.2.6 on 2019-10-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_clientinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_name', models.CharField(default='请在后台修改公司名称', max_length=20, verbose_name='公司名称')),
                ('my_email', models.EmailField(max_length=254, verbose_name='公司邮箱')),
                ('my_phone', models.CharField(default='15924239167', max_length=11, verbose_name='公司电话')),
                ('my_qq', models.CharField(default='303070738', max_length=12, verbose_name='公司QQ')),
            ],
            options={
                'verbose_name': '本公司信息',
                'verbose_name_plural': '本公司信息',
            },
        ),
        migrations.AlterModelOptions(
            name='clientinfo',
            options={'verbose_name': '客户留言', 'verbose_name_plural': '客户留言(时不时看一下，可能会有客户留言)'},
        ),
    ]
