# Generated by Django 2.2.6 on 2019-10-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191018_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycompanyinfo',
            name='my_add',
            field=models.CharField(blank=True, default='City of the Hill', max_length=30, verbose_name='公司地址'),
        ),
    ]
