# Generated by Django 2.2.6 on 2019-10-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_mycompanyinfo_my_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompanyinfo',
            name='my_email',
            field=models.EmailField(default='请在后台修改公司信息', max_length=254, verbose_name='公司邮箱'),
        ),
    ]
